# modmap:
#   - name: Except Chrome
#     application:
#       not: Google-chrome
#     remap:
#       CapsLock: Esc
# device:
#   only: ''
keymap:
  - name: Emacs binding
    application:
      only: [firefox, Google-chrome, systemsettings]
    remap:
      M-h: left
      M-l: right
      M-k: up
      M-j: down

